## NumPy exercises

In [628]:
import numpy as np
print(np.__version__)

1.26.4


### Array creation

#### `Create a numpy array of size 10, filled with zeros.`

In [629]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### `Create a numpy array with values ranging from 10 to 49`

In [630]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### `Create a numpy matrix of 2*2 integers, filled with ones.`

In [631]:
np.ones([2, 2], dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

#### `Create a numpy matrix of 3*2 float numbers, filled with ones.`

In [632]:
np.ones([3, 2], dtype=np.float32)

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

#### `Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.`

In [633]:
X = np.arange(4, dtype=np.int8)

np.ones_like(X)

array([1, 1, 1, 1], dtype=int8)

#### `Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.`

In [634]:
X = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int8)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

#### `Create a numpy matrix of 4*4 integers, filled with fives.`

In [635]:
np.ones([4,4], dtype=np.int8) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

#### `Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.`

In [636]:
X = np.array([[2, 3], [6, 2]], dtype=np.int8)
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]], dtype=int8)

#### `Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.`

In [637]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### `Create a numpy array, filled with 3 random integer values between 1 and 10.`

In [638]:
np.random.randint(10, size=3) # random integers between 0 and 10

array([7, 1, 1])

#### `Create a 3*3*3 numpy matrix, filled with random float values.`

In [639]:
np.random.randn(3,3,3) # 3D matrix with random numbers from standard normal distribution with 3 rows and 3 columns

array([[[-1.56188214,  0.08565768,  0.47924842],
        [ 0.94132285, -0.40572324,  0.1434737 ],
        [ 0.03748237,  1.28206226,  0.29443745]],

       [[-0.75434319,  0.5496658 ,  1.0978893 ],
        [-1.1517885 , -0.38091879, -1.09341743],
        [ 0.2282359 ,  0.28213892,  0.19043361]],

       [[-0.10070478,  0.97163694,  0.51478335],
        [-0.17477368,  0.74152995,  1.2451048 ],
        [ 1.30485449, -0.53947393, -0.39816503]]])

#### `Given the X python list convert it to an Y numpy array`

In [640]:
X = [3, 4, 7]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))  # different type

[3, 4, 7] <class 'list'>
[3 4 7] <class 'numpy.ndarray'>


#### `Given the X numpy array, make a copy and store it on Y.`

In [641]:
X = np.array([5, 2, 3], dtype=np.int8)
print(X, id(X))
Y = np.copy(X)
print(Y, id(Y))  # different id

[5 2 3] 2617095225776
[5 2 3] 2617094869264


#### `Create a numpy array with numbers from 1 to 10`

In [642]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### `Create a numpy array with the odd numbers between 1 to 10`

In [643]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

#### `Create a numpy array with numbers from 1 to 10, in descending order.`

In [644]:
X = np.arange(1, 11)
X[::-1]  # slicing in reverse order

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### `Create a 3*3 numpy matrix, filled with values ranging from 0 to 8`

In [645]:
np.arange(9).reshape(3, 3) # 3x3 matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### `Show the memory size of the given Z numpy matrix`

In [646]:
Z = np.zeros((10, 10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


---

### Array indexation

#### `Given the X numpy array, show it's first element`

In [647]:
X = np.array(["A", "B", "C", "D", "E"])

X[0]

'A'

#### `Given the X numpy array, show it's last element`

In [648]:
X = np.array(["A", "B", "C", "D", "E"])

X[-1]  # last element

'E'

#### `Given the X numpy array, show it's first three elements`

In [649]:
X = np.array(["A", "B", "C", "D", "E"])
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

#### `Given the X numpy array, show all middle elements`

In [650]:
X = np.array(["A", "B", "C", "D", "E"])
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

#### `Given the X numpy array, show the elements in reverse position`

In [651]:
X = np.array(["A", "B", "C", "D", "E"])
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

#### `Given the X numpy array, show the elements in an odd position`

In [652]:
X = np.array(["A", "B", "C", "D", "E"])
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

#### `Given the X numpy matrix, show the first row elements`

In [653]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

X[0]

array([1, 2, 3, 4])

#### `Given the X numpy matrix, show the last row elements`

In [654]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

X[-1]

array([13, 14, 15, 16])

#### `Given the X numpy matrix, show the first element on first row`

In [655]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X[0,0] 

1

#### `Given the X numpy matrix, show the last element on last row`

In [656]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X[-1, -1]

16

#### `Given the X numpy matrix, show the middle row elements`

In [657]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

#### `Given the X numpy matrix, show the first two elements on the first two rows`

In [658]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X[:2, :2]

array([[1, 2],
       [5, 6]])

#### `Given the X numpy matrix, show the last two elements on the last two rows`

In [659]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

---

### Array manipulation

#### `Convert the given integer numpy array to float` 

In [660]:
X = [-5, -3, 0, 10, 40]

np.array(X, dtype=np.float32)

array([-5., -3.,  0., 10., 40.], dtype=float32)

#### `Reverse the given numpy array (first element becomes last)` 

In [661]:
X = [-5, -3, 0, 10, 40]
# X[::-1]
X[len(X)-1::-1] 

[40, 10, 0, -3, -5]

#### `Order (sort) the given numpy array` 

In [662]:
X = [0, 10, -5, 40, -3]
X.sort() 
X

[-5, -3, 0, 10, 40]

#### `Given the X numpy array, set the fifth element equal to 1` 

In [663]:
X = np.arange(10)

X[4] = 1
X

array([0, 1, 2, 3, 1, 5, 6, 7, 8, 9])

#### `Given the X numpy array, change the 50 with a 40` 

In [664]:
X = np.array([10, 20, 30, 50])

X[X == 50] = 40  #finding the first element equal to 50 and replacing it with 40
X

array([10, 20, 30, 40])

#### `Given the X numpy matrix, change the last row with all 1` 

In [665]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

#### `Given the X numpy matrix, change the last item on the last row with a 0` 

In [666]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

#### `Given the X numpy matrix, add 5 to every element` 

In [667]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

---

### Boolean arrays (also called masks)

#### `Given the X numpy array, make a mask showing negative elements` 

In [668]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X < 0 
mask

array([ True, False, False,  True, False, False, False, False,  True,
       False])

#### `Given the X numpy array, get the negative elements` 

In [669]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X < 0
X[mask]

array([-1, -4, -9])

#### `Given the X numpy array, get numbers higher than 5` 

In [670]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

#### `Given the X numpy array, get numbers higher than the elements mean` 

In [671]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

#### `Given the X numpy array, get numbers equal to 2 or 10` 

In [672]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

---

### Logic functions

#### `Given the X numpy array, return True if none of its elements is zero` 

In [673]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X.all() # all elements are non-zero 

False

#### `Given the X numpy array, return True if any of its elements is zero`

In [674]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

---

### Summary statistics

#### `Given the X numpy array, show the sum of its elements`

In [675]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X.sum()

43

#### `Given the X numpy array, show the mean value of its elements`

In [676]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
X.mean()

3.7

#### `Given the X numpy matrix, show the sum of its columns`

In [677]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

X.sum(axis=0)  #axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

#### `Given the X numpy matrix, show the mean value of its rows`

In [678]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

X.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

#### `Given the X numpy array, show the max value of its elements`

In [679]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
X.max()

10